# import requests
# url="https://opentdb.com/api.php?amount=10&type=boolean"
# response=requests.get(url=url)
# data=response.json()
# print(data)



qns = [{"type":"boolean","difficulty":"medium","category":"History","question":"In 1967, a magazine published a story about extracting hallucinogenic chemicals from bananas to raise moral questions about banning drugs.","correct_answer":"True","incorrect_answers":["False"]},{"type":"boolean","difficulty":"medium","category":"History","question":"The first televised presidential debate was between Jimmy Carter and Gerald Ford.","correct_answer":"False","incorrect_answers":["True"]},{"type":"boolean","difficulty":"medium","category":"History","question":"In World War II, Hawker Typhoons served in the Pacific theater.","correct_answer":"False","incorrect_answers":["True"]},{"type":"boolean","difficulty":"medium","category":"History","question":"The M41 Walker Bulldog remains in service in some countries to this day.","correct_answer":"True","incorrect_answers":["False"]},{"type":"boolean","difficulty":"medium","category":"History","question":"Theodore Roosevelt Jr. was the only General involved in the initial assault on D-Day.","correct_answer":"True","incorrect_answers":["False"]},{"type":"boolean","difficulty":"medium","category":"History","question":"The Korean War ended in 1953 without any ceasefire.","correct_answer":"False","incorrect_answers":["True"]},{"type":"boolean","difficulty":"medium","category":"History","question":"Sargon II, a king of the Neo-Assyrian Empire, was a direct descendant of Sargon of Akkad.","correct_answer":"False","incorrect_answers":["True"]},{"type":"boolean","difficulty":"medium","category":"History","question":"The Hundred Years; War was fought for more than a hundred years.","correct_answer":"True","incorrect_answers":["False"]},{"type":"boolean","difficulty":"medium","category":"History","question":"Franz Joseph I was the last emperor of Austria.","correct_answer":"False","incorrect_answers":["True"]},{"type":"boolean","difficulty":"medium","category":"History","question":"Augustus was the cousin of Julius Caesar. ","correct_answer":"False","incorrect_answers":["True"]}]

